name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-sonar:
    name: Build, Test and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      #  Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Installer l'Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.3

      # Rendre Gradle exécutable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Déchiffrer `google-services.json`
      - name: Decode google-services.json
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Decode Firebase Admin SDK
        run: |
          echo $FIREBASE_AUTH_TOKEN | base64 --decode > app/firebase-adminsdk.json
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase CLI
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=app/firebase-adminsdk.json
      - name: Verify Firebase Credentials File
        run: ls -l app/firebase-adminsdk.json

      - name: Debug GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GOOGLE_APPLICATION_CREDENTIALS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: app/firebase-adminsdk.json

      - name: Generate debug keystore
        run: |
          mkdir -p ~/.config/.android
          keytool -genkey -v -keystore ~/.config/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000


      - name: Set File Permissions
        run: chmod 600 app/firebase-adminsdk.json

      # Construire le projet avec Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Debug APK Paths
        run: ls -R app/build/outputs/apk/

      # Exécuter les tests unitaires
      - name: Run Unit Tests
        run: ./gradlew test

      # Analyse avec SonarCloud
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar


      - name: Display Firebase Admin SDK Content
        run: cat app/firebase-adminsdk.json

      - name: Upload APK to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: app/firebase-adminsdk.json
        run: ./gradlew appDistributionUploadDebug