name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-sonar:
    name: Build, Test and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      #  Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Installer l'Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.3

      # Rendre Gradle exécutable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Déchiffrer `google-services.json`
      - name: Decode google-services.json
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      # Construire le projet avec Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Exécuter les tests unitaires
      - name: Run Unit Tests
        run: ./gradlew test

      # Analyse avec SonarCloud
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar